application: jgsuicidepool
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: pycrypto
  version: "latest"

- name: django
  version: "latest"

handlers:
- url: /results.*
  script: handlers.results.app

- url: /rules.*
  script: handlers.main.app

- url: /picks.*
  script: handlers.picks.app

- url: /games.*
  script: handlers.games.app

- url: /setup.*
  script: handlers.setup.app

- url: /admin.*
  script: handlers.admin.app

- url: /users.*
  script: handlers.users.app

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /login.*
  script: handlers.main.app

- url: /logout
  script: handlers.main.app

- url: /.*
  script: handlers.main.app

# TODO: add robots file

skip_files:
- ^old/
#- ^Crypto/
- (.*\.py[co])

