application: jgsuicidepool
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- deferred: on
- appstats: on

libraries:
- name: pycrypto
  version: "latest"

- name: django
  version: "latest"

- name: lxml
  version: "latest"

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app

- url: /results.*
  script: handlers.results.app

- url: /analysis.*
  script: handlers.analysis.app

- url: /rules.*
  script: handlers.main.app

- url: /picks.*
  script: handlers.picks.app

- url: /games.*
  script: handlers.games.app

- url: /setup.*
  script: handlers.setup.app

- url: /admin.*
  script: handlers.admin.app

- url: /users.*
  script: handlers.users.app

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /login.*
  script: handlers.main.app

- url: /logout
  script: handlers.main.app

- url: /
  script: handlers.main.app

skip_files:
- ^old/
- ^lib/
- ^bin/
- ^Crypto/
- (.*\.py[co])

