application: iernst-football2
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: pycrypto
  version: "2.3"

handlers:
- url: /standings.*
  script: handlers.standings.app

- url: /rules.*
  script: handlers.rules.app

- url: /picks.*
  script: handlers.picks.app

- url: /games.*
  script: handlers.games.app

- url: /user.*
  script: handlers.user.app

- url: /admin.*
  script: handlers.admin.app

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /.*
  script: handlers.home.app

# TODO: add robots file
